import type { NailDesign } from "./types";

export const DESIGNS: NailDesign[] = [
  {
    id: "1",
    name: "Pink French Tips",
    category: "Elegant",
    colors: ["#f9a8d4", "#ffffff", "#fce7f3"],
    style: "French",
    difficulty: "Easy",
    description: "Classic white tips softened with a baby-pink base for a timeless feminine look.",
    tags: ["french", "pink", "classic", "wedding"],
    image: "pink-french-tips",
  },
  {
    id: "2",
    name: "Coquette Bow Nails",
    category: "Cute",
    colors: ["#fbcfe8", "#ffffff", "#e879a8"],
    style: "Coquette",
    difficulty: "Medium",
    description: "Sheer blush nails finished with tiny hand-painted bows for a romantic coquette vibe.",
    tags: ["bows", "coquette", "pink", "romantic"],
    image: "coquette-bow-nails",
  },
  {
    id: "3",
    name: "Butterfly Pastel Nails",
    category: "Y2K",
    colors: ["#a5f3fc", "#fbcfe8", "#fef9c3"],
    style: "Y2K Butterfly",
    difficulty: "Medium",
    description: "Iridescent pastel base with delicate butterfly wing accents on each nail.",
    tags: ["butterfly", "pastel", "y2k", "shimmer"],
    image: "butterfly-pastel-nails",
  },
  {
    id: "4",
    name: "Strawberry Nails",
    category: "Food",
    colors: ["#ef4444", "#22c55e", "#ffffff"],
    style: "Fruit Art",
    difficulty: "Medium",
    description: "Glossy red nails dotted with strawberry seeds and tiny green leaf tips.",
    tags: ["strawberry", "fruit", "summer", "kawaii"],
    image: "strawberry-nails",
  },
  {
    id: "5",
    name: "Tulip Nails",
    category: "Floral",
    colors: ["#f472b6", "#86efac", "#fef3c7"],
    style: "Floral",
    difficulty: "Medium",
    description: "Creamy nude base blooming with pink tulips and soft green stems.",
    tags: ["tulip", "floral", "spring", "garden"],
    image: "tulip-nails",
  },
  {
    id: "6",
    name: "Rose Nails",
    category: "Floral",
    colors: ["#e11d48", "#fda4af", "#14532d"],
    style: "Floral",
    difficulty: "Hard",
    description: "Deep rose-red petals layered over blush with fine botanical detailing.",
    tags: ["rose", "floral", "romantic", "elegant"],
    image: "rose-nails",
  },
  {
    id: "7",
    name: "Daisy Nails",
    category: "Floral",
    colors: ["#ffffff", "#fde047", "#bae6fd"],
    style: "Floral",
    difficulty: "Easy",
    description: "Cheerful white daisies with sunny yellow centers on a sky-blue wash.",
    tags: ["daisy", "floral", "summer", "fresh"],
    image: "daisy-nails",
  },
  {
    id: "8",
    name: "Cloud Nails",
    category: "Kawaii",
    colors: ["#bae6fd", "#ffffff", "#e0e7ff"],
    style: "Kawaii Sky",
    difficulty: "Easy",
    description: "Dreamy sky-blue gradient with puffy white clouds drifting across each tip.",
    tags: ["cloud", "sky", "kawaii", "dreamy"],
    image: "cloud-nails",
  },
  {
    id: "9",
    name: "Rainbow Pastel Nails",
    category: "Kawaii",
    colors: ["#fbcfe8", "#fef9c3", "#bbf7d0"],
    style: "Rainbow",
    difficulty: "Easy",
    description: "Skittle-style pastel rainbow with one soft candy shade per nail.",
    tags: ["rainbow", "pastel", "colorful", "kawaii"],
    image: "rainbow-pastel-nails",
  },
  {
    id: "10",
    name: "Heart French Tips",
    category: "Cute",
    colors: ["#fb7185", "#ffffff", "#ffe4e6"],
    style: "French Hearts",
    difficulty: "Medium",
    description: "White French tips reshaped into tiny hearts over a sheer rosy base.",
    tags: ["hearts", "french", "valentine", "cute"],
    image: "heart-french-tips",
  },
  {
    id: "11",
    name: "Pink Chrome",
    category: "Chrome",
    colors: ["#f9a8d4", "#fdf2f8", "#ec4899"],
    style: "Pink Chrome",
    difficulty: "Medium",
    description: "Molten pink chrome with a mirror glaze that shifts from blush to fuchsia.",
    tags: ["chrome", "pink", "glazed", "shiny"],
    image: "pink-chrome",
  },
  {
    id: "12",
    name: "Silver Chrome",
    category: "Chrome",
    colors: ["#e5e7eb", "#ffffff", "#9ca3af"],
    style: "Silver Chrome",
    difficulty: "Medium",
    description: "Liquid-silver mirror nails with an icy high-shine metallic finish.",
    tags: ["chrome", "silver", "metallic", "mirror"],
    image: "silver-chrome",
  },
  {
    id: "13",
    name: "Glazed Donut",
    category: "Chrome",
    colors: ["#fde68a", "#fffbeb", "#f472b6"],
    style: "Glazed Chrome",
    difficulty: "Easy",
    description: "Hailey Bieber-inspired pearly glaze over a milky nude base.",
    tags: ["glazed", "chrome", "pearl", "nude"],
    image: "glazed-donut",
  },
  {
    id: "14",
    name: "Lavender Chrome",
    category: "Chrome",
    colors: ["#c4b5fd", "#ede9fe", "#8b5cf6"],
    style: "Lavender Chrome",
    difficulty: "Medium",
    description: "Dreamy lilac chrome with an opalescent violet shimmer.",
    tags: ["chrome", "lavender", "purple", "shimmer"],
    image: "lavender-chrome",
  },
  {
    id: "15",
    name: "Blue Chrome",
    category: "Chrome",
    colors: ["#93c5fd", "#eff6ff", "#2563eb"],
    style: "Blue Chrome",
    difficulty: "Medium",
    description: "Electric sapphire chrome polished to a glassy ocean shine.",
    tags: ["chrome", "blue", "metallic", "ocean"],
    image: "blue-chrome",
  },
  {
    id: "16",
    name: "Pearl Chrome",
    category: "Elegant",
    colors: ["#fdf4ff", "#ffffff", "#e9d5ff"],
    style: "Pearl Chrome",
    difficulty: "Easy",
    description: "Lustrous white pearl chrome with a soft bridal glow.",
    tags: ["pearl", "chrome", "white", "bridal"],
    image: "pearl-chrome",
  },
  {
    id: "17",
    name: "Fairy Dust Nails",
    category: "Cute",
    colors: ["#fbcfe8", "#fef9c3", "#e0e7ff"],
    style: "Fairy Glitter",
    difficulty: "Easy",
    description: "Sheer fairy-pink base scattered with holographic star dust.",
    tags: ["fairy", "glitter", "stars", "sparkle"],
    image: "fairy-dust-nails",
  },
  {
    id: "18",
    name: "Starry Night Nails",
    category: "Gothic",
    colors: ["#1e1b4b", "#fde68a", "#c4b5fd"],
    style: "Starry Night",
    difficulty: "Hard",
    description: "Midnight indigo nails flecked with gold constellations and tiny stars.",
    tags: ["stars", "night", "dark", "celestial"],
    image: "starry-night-nails",
  },
  {
    id: "19",
    name: "Moon & Stars",
    category: "Minimalist",
    colors: ["#fef3c7", "#fde68a", "#78350f"],
    style: "Celestial",
    difficulty: "Easy",
    description: "Milky nude nails stamped with gold crescent moons and starbursts.",
    tags: ["moon", "stars", "gold", "celestial"],
    image: "moon-and-stars",
  },
  {
    id: "20",
    name: "Crystal Nails",
    category: "Elegant",
    colors: ["#e0f2fe", "#ffffff", "#a5f3fc"],
    style: "Crystal Jewels",
    difficulty: "Hard",
    description: "Icy glass nails crowned with faceted crystal gems that catch the light.",
    tags: ["crystal", "gems", "glam", "jewels"],
    image: "crystal-nails",
  },
  {
    id: "21",
    name: "Milky White Nails",
    category: "Minimalist",
    colors: ["#faf9f7", "#ffffff", "#e7e5e4"],
    style: "Milky Minimal",
    difficulty: "Easy",
    description: "Sheer milky-white wash with a glassy finish for the ultimate clean-girl manicure.",
    tags: ["white", "milky", "minimal", "clean"],
    image: "milky-white-nails",
  },
  {
    id: "22",
    name: "Vanilla Cream Nails",
    category: "Elegant",
    colors: ["#fef3c7", "#fffbeb", "#f5e6c8"],
    style: "Cream Solid",
    difficulty: "Easy",
    description: "Warm vanilla-cream creme that flatters every skin tone with quiet luxury.",
    tags: ["vanilla", "cream", "nude", "elegant"],
    image: "vanilla-cream-nails",
  },
  {
    id: "23",
    name: "Peach Nude Nails",
    category: "Elegant",
    colors: ["#fdba74", "#ffedd5", "#fb923c"],
    style: "Peach Solid",
    difficulty: "Easy",
    description: "Soft peachy-nude creme with a juicy glow that reads fresh year-round.",
    tags: ["peach", "nude", "spring", "fresh"],
    image: "peach-nude-nails",
  },
  {
    id: "24",
    name: "Chocolate Brown Nails",
    category: "Food",
    colors: ["#78350f", "#a16207", "#451a03"],
    style: "Chocolate Glaze",
    difficulty: "Easy",
    description: "Rich molten-chocolate brown polished to a decadent high-shine glaze.",
    tags: ["chocolate", "brown", "fall", "glossy"],
    image: "chocolate-brown-nails",
  },
  {
    id: "25",
    name: "Mocha Nails",
    category: "Food",
    colors: ["#a8a29e", "#d6c7b8", "#78716c"],
    style: "Mocha Swirl",
    difficulty: "Medium",
    description: "Creamy mocha latte swirls blending espresso and steamed-milk tones.",
    tags: ["mocha", "coffee", "swirl", "nude"],
    image: "mocha-nails",
  },
  {
    id: "26",
    name: "Teddy Bear Nails",
    category: "Cute",
    colors: ["#d6a87c", "#8b5e34", "#fff7ed"],
    style: "Teddy Bear",
    difficulty: "Medium",
    description: "Cuddly caramel teddy faces with round ears on a toasted-nude base.",
    tags: ["teddy", "bear", "cute", "kawaii"],
    image: "teddy-bear-nails",
  },
  {
    id: "27",
    name: "Bear Face Nails",
    category: "Kawaii",
    colors: ["#b08968", "#7f5539", "#ede0d4"],
    style: "Bear Face",
    difficulty: "Medium",
    description: "Sleepy kawaii bear faces with blush cheeks dotted across each nail.",
    tags: ["bear", "kawaii", "face", "cute"],
    image: "bear-face-nails",
  },
  {
    id: "28",
    name: "Bunny Nails",
    category: "Cute",
    colors: ["#fce7f3", "#ffffff", "#f9a8d4"],
    style: "Bunny Face",
    difficulty: "Medium",
    description: "Sweet white bunny faces with long ears and pink noses on blush pink.",
    tags: ["bunny", "rabbit", "easter", "cute"],
    image: "bunny-nails",
  },
  {
    id: "29",
    name: "Cat Nails",
    category: "Kawaii",
    colors: ["#e7e5e4", "#44403c", "#fbbf24"],
    style: "Cat Face",
    difficulty: "Medium",
    description: "Mischievous kitty faces with whiskers and pointy ears in tabby grey.",
    tags: ["cat", "kitty", "whiskers", "kawaii"],
    image: "cat-nails",
  },
  {
    id: "30",
    name: "Panda Nails",
    category: "Cute",
    colors: ["#ffffff", "#18181b", "#e4e4e7"],
    style: "Panda Face",
    difficulty: "Medium",
    description: "Chubby panda faces with inky eye patches on a crisp white base.",
    tags: ["panda", "black-white", "cute", "animal"],
    image: "panda-nails",
  },
  {
    id: "31",
    name: "Cherry Nails",
    category: "Food",
    colors: ["#dc2626", "#166534", "#fef2f2"],
    style: "Cherry Fruit",
    difficulty: "Medium",
    description: "Glossy cherry pairs with curling green stems on a milky sheer base.",
    tags: ["cherry", "fruit", "summer", "retro"],
    image: "cherry-nails",
  },
  {
    id: "32",
    name: "Lemon Nails",
    category: "Food",
    colors: ["#fde047", "#fefce8", "#16a34a"],
    style: "Lemon Fruit",
    difficulty: "Medium",
    description: "Zesty lemon wedges with leafy sprigs scattered over sunny yellow.",
    tags: ["lemon", "citrus", "summer", "fruit"],
    image: "lemon-nails",
  },
  {
    id: "33",
    name: "Orange Nails",
    category: "Food",
    colors: ["#fb923c", "#fff7ed", "#22c55e"],
    style: "Orange Fruit",
    difficulty: "Medium",
    description: "Juicy orange slices with segmented citrus detail on a creamsicle base.",
    tags: ["orange", "citrus", "fruit", "summer"],
    image: "orange-nails",
  },
  {
    id: "34",
    name: "Blueberry Nails",
    category: "Food",
    colors: ["#4c1d95", "#a5b4fc", "#1e3a8a"],
    style: "Blueberry Fruit",
    difficulty: "Hard",
    description: "Dusty-indigo blueberries with tiny star crowns on a periwinkle wash.",
    tags: ["blueberry", "fruit", "purple", "berry"],
    image: "blueberry-nails",
  },
  {
    id: "35",
    name: "Watermelon Nails",
    category: "Food",
    colors: ["#f87171", "#22c55e", "#18181b"],
    style: "Watermelon Fruit",
    difficulty: "Medium",
    description: "Picnic-ready watermelon slices with seed dots and green rind tips.",
    tags: ["watermelon", "fruit", "summer", "fun"],
    image: "watermelon-nails",
  },
  {
    id: "36",
    name: "Kiwi Nails",
    category: "Food",
    colors: ["#65a30d", "#d9f99d", "#365314"],
    style: "Kiwi Fruit",
    difficulty: "Medium",
    description: "Tangy kiwi slices with speckled seeds over a juicy lime-green base.",
    tags: ["kiwi", "fruit", "green", "summer"],
    image: "kiwi-nails",
  },
  {
    id: "37",
    name: "Grape Nails",
    category: "Food",
    colors: ["#7c3aed", "#c4b5fd", "#16a34a"],
    style: "Grape Fruit",
    difficulty: "Medium",
    description: "Plump purple grape clusters with curly vines on a lilac wash.",
    tags: ["grape", "fruit", "purple", "vineyard"],
    image: "grape-nails",
  },
  {
    id: "38",
    name: "Apple Nails",
    category: "Food",
    colors: ["#dc2626", "#16a34a", "#fef2f2"],
    style: "Apple Fruit",
    difficulty: "Easy",
    description: "Shiny red apples with a single green leaf on a crisp orchard base.",
    tags: ["apple", "fruit", "red", "fall"],
    image: "apple-nails",
  },
  {
    id: "39",
    name: "Cupcake Nails",
    category: "Food",
    colors: ["#f9a8d4", "#fef3c7", "#ec4899"],
    style: "Cupcake Party",
    difficulty: "Hard",
    description: "Frosted cupcakes with sprinkles and a cherry top on candy pink.",
    tags: ["cupcake", "sweet", "party", "pink"],
    image: "cupcake-nails",
  },
  {
    id: "40",
    name: "Cake Nails",
    category: "Food",
    colors: ["#fbcfe8", "#ffffff", "#e879a8"],
    style: "Birthday Cake",
    difficulty: "Hard",
    description: "Layered birthday-cake slices with dripping icing and confetti dots.",
    tags: ["cake", "birthday", "party", "sweet"],
    image: "cake-nails",
  },
  {
    id: "41",
    name: "Kawaii Nails",
    category: "Kawaii",
    colors: ["#fbcfe8", "#fef9c3", "#bae6fd"],
    style: "Kawaii Party",
    difficulty: "Easy",
    description: "Bubbly pastel kawaii faces, hearts, and stars on a marshmallow base.",
    tags: ["kawaii", "cute", "pastel", "decora"],
    image: "kawaii-nails",
  },
  {
    id: "42",
    name: "Pink Y2K Nails",
    category: "Y2K",
    colors: ["#f9a8d4", "#e0e7ff", "#a855f7"],
    style: "Pink Y2K",
    difficulty: "Medium",
    description: "Hot-pink Y2K stickers, starbursts, and swirls with a frosted shine.",
    tags: ["y2k", "pink", "retro", "stickers"],
    image: "pink-y2k-nails",
  },
  {
    id: "43",
    name: "Y2K Chrome Nails",
    category: "Chrome",
    colors: ["#c4b5fd", "#fdf4ff", "#6366f1"],
    style: "Y2K Chrome",
    difficulty: "Hard",
    description: "Holographic lilac chrome stamped with silver Y2K star charms.",
    tags: ["y2k", "chrome", "holographic", "stars"],
    image: "y2k-chrome-nails",
  },
  {
    id: "44",
    name: "Unicorn Nails",
    category: "Kawaii",
    colors: ["#fbcfe8", "#e0e7ff", "#fde68a"],
    style: "Unicorn Magic",
    difficulty: "Hard",
    description: "Twirly unicorn horns with rainbow manes on a dreamy pastel base.",
    tags: ["unicorn", "magic", "rainbow", "fantasy"],
    image: "unicorn-nails",
  },
  {
    id: "45",
    name: "Mermaid Nails",
    category: "Kawaii",
    colors: ["#5eead4", "#a5f3fc", "#8b5cf6"],
    style: "Mermaid Scales",
    difficulty: "Hard",
    description: "Iridescent mermaid scales with a lustrous pearl accent on seafoam.",
    tags: ["mermaid", "scales", "ocean", "shimmer"],
    image: "mermaid-nails",
  },
  {
    id: "46",
    name: "Fairy Nails",
    category: "Floral",
    colors: ["#fbcfe8", "#d1fae5", "#ffffff"],
    style: "Fairy Wings",
    difficulty: "Hard",
    description: "Gossamer fairy wings with petal sparkle trailing over blush green.",
    tags: ["fairy", "wings", "garden", "magic"],
    image: "fairy-nails",
  },
  {
    id: "47",
    name: "Ocean Nails",
    category: "Minimalist",
    colors: ["#38bdf8", "#e0f2fe", "#0c4a6e"],
    style: "Ocean Waves",
    difficulty: "Easy",
    description: "Minimal navy wave lines rolling across a sea-glass blue base.",
    tags: ["ocean", "waves", "blue", "beach"],
    image: "ocean-nails",
  },
  {
    id: "48",
    name: "Seashell Nails",
    category: "Elegant",
    colors: ["#fde68a", "#fffbeb", "#f9a8d4"],
    style: "Seashell Shimmer",
    difficulty: "Medium",
    description: "Pearlescent fan shells with gold ridges on warm beach sand.",
    tags: ["seashell", "pearl", "beach", "elegant"],
    image: "seashell-nails",
  },
  {
    id: "49",
    name: "Coral Nails",
    category: "Floral",
    colors: ["#fb7185", "#fda4af", "#0d9488"],
    style: "Coral Reef",
    difficulty: "Medium",
    description: "Branching blush coral with sea-green fronds on a reef pastel.",
    tags: ["coral", "reef", "ocean", "botanical"],
    image: "coral-nails",
  },
  {
    id: "50",
    name: "Ocean Fish Nails",
    category: "Cute",
    colors: ["#38bdf8", "#fef9c3", "#f97316"],
    style: "Ocean Fish",
    difficulty: "Medium",
    description: "Bubbles and a tangerine fish darting across bright lagoon blue.",
    tags: ["fish", "ocean", "cute", "sea"],
    image: "ocean-fish-nails",
  },
  {
    id: "51",
    name: "Tropical Flowers",
    category: "Floral",
    colors: ["#f472b6", "#22c55e", "#fefce8"],
    style: "Tropical Floral",
    difficulty: "Medium",
    description: "Bold hibiscus blooms with lush palm leaves on creamy coconut white.",
    tags: ["hibiscus", "tropical", "floral", "vacation"],
    image: "tropical-flowers",
  },
  {
    id: "52",
    name: "Palm Tree Nails",
    category: "Minimalist",
    colors: ["#fdba74", "#451a03", "#fef3c7"],
    style: "Palm Silhouette",
    difficulty: "Medium",
    description: "Black palm silhouettes swaying over a warm sunset gradient.",
    tags: ["palm", "sunset", "beach", "silhouette"],
    image: "palm-tree-nails",
  },
  {
    id: "53",
    name: "Sunset Nails",
    category: "Elegant",
    colors: ["#fb923c", "#f472b6", "#7c3aed"],
    style: "Sunset Ombre",
    difficulty: "Easy",
    description: "Golden-hour ombre melting from tangerine through rose to violet.",
    tags: ["sunset", "ombre", "gradient", "summer"],
    image: "sunset-nails",
  },
  {
    id: "54",
    name: "Galaxy Nails",
    category: "Gothic",
    colors: ["#1e1b4b", "#7c3aed", "#f0abfc"],
    style: "Galaxy Swirl",
    difficulty: "Hard",
    description: "Deep-space nebula swirls with violet stars on midnight indigo.",
    tags: ["galaxy", "space", "dark", "nebula"],
    image: "galaxy-nails",
  },
  {
    id: "55",
    name: "Shooting Star Nails",
    category: "Kawaii",
    colors: ["#1e3a8a", "#fde68a", "#ffffff"],
    style: "Shooting Stars",
    difficulty: "Medium",
    description: "Gold shooting stars streaking across a midnight-blue sky.",
    tags: ["stars", "night", "wishes", "sparkle"],
    image: "shooting-star-nails",
  },
  {
    id: "56",
    name: "Flame Nails",
    category: "Y2K",
    colors: ["#f97316", "#fde047", "#18181b"],
    style: "Flame Tips",
    difficulty: "Hard",
    description: "Licking orange flames rising over jet-black almond tips.",
    tags: ["flames", "fire", "black", "y2k"],
    image: "flame-nails",
  },
  {
    id: "57",
    name: "Black French Tips",
    category: "Gothic",
    colors: ["#18181b", "#3f3f46", "#a1a1aa"],
    style: "Black French",
    difficulty: "Easy",
    description: "Sharp jet-black tips over smoked nude for a moody French twist.",
    tags: ["french", "black", "goth", "chic"],
    image: "black-french-tips",
  },
  {
    id: "58",
    name: "Red French Tips",
    category: "Gothic",
    colors: ["#7f1d1d", "#dc2626", "#fecaca"],
    style: "Red French",
    difficulty: "Easy",
    description: "Blood-red French tips over deep noir with a vinyl shine.",
    tags: ["french", "red", "vamp", "dark"],
    image: "red-french-tips",
  },
  {
    id: "59",
    name: "Burgundy Nails",
    category: "Elegant",
    colors: ["#581c1c", "#991b1b", "#3f1010"],
    style: "Burgundy Gloss",
    difficulty: "Easy",
    description: "Ox-blood burgundy gloss with wine-dark depth for evening looks.",
    tags: ["burgundy", "wine", "fall", "elegant"],
    image: "burgundy-nails",
  },
  {
    id: "60",
    name: "Gothic Lace Nails",
    category: "Gothic",
    colors: ["#18181b", "#e4e4e7", "#52525b"],
    style: "Gothic Lace",
    difficulty: "Hard",
    description: "White lace filigree traced over matte black for Victorian drama.",
    tags: ["lace", "goth", "victorian", "black"],
    image: "gothic-lace-nails",
  },
  {
    id: "61",
    name: "Spider Web Nails",
    category: "Gothic",
    colors: ["#27272a", "#ffffff", "#a1a1aa"],
    style: "Spider Web",
    difficulty: "Medium",
    description: "Silver cobwebs spun from the cuticle over smoky charcoal.",
    tags: ["spider", "web", "halloween", "goth"],
    image: "spider-web-nails",
  },
  {
    id: "62",
    name: "Dark Rose Nails",
    category: "Gothic",
    colors: ["#3f1010", "#991b1b", "#166534"],
    style: "Dark Rose",
    difficulty: "Hard",
    description: "Blackened crimson roses with thorny stems on near-black plum.",
    tags: ["rose", "dark", "goth", "romantic"],
    image: "dark-rose-nails",
  },
  {
    id: "63",
    name: "Vampire Nails",
    category: "Gothic",
    colors: ["#450a0a", "#dc2626", "#fef2f2"],
    style: "Vampire Drip",
    difficulty: "Medium",
    description: "Glossy blood-red drips falling over a dark maroon base.",
    tags: ["vampire", "blood", "halloween", "drip"],
    image: "vampire-nails",
  },
  {
    id: "64",
    name: "Black & Red Nails",
    category: "Gothic",
    colors: ["#18181b", "#b91c1c", "#ef4444"],
    style: "Black Red Split",
    difficulty: "Medium",
    description: "Half-and-half noir and scarlet split down the center of each nail.",
    tags: ["black", "red", "split", "alt"],
    image: "black-red-nails",
  },
  {
    id: "65",
    name: "Leopard Print",
    category: "Y2K",
    colors: ["#d4a373", "#7c2d12", "#18181b"],
    style: "Leopard Spots",
    difficulty: "Hard",
    description: "Golden-tan base scattered with broken black rosettes, pure attitude.",
    tags: ["leopard", "print", "animal", "wild"],
    image: "leopard-print",
  },
  {
    id: "66",
    name: "Snake Print",
    category: "Y2K",
    colors: ["#a8a29e", "#44403c", "#65a30d"],
    style: "Snake Scales",
    difficulty: "Hard",
    description: "Slithering scale rows in stone grey with a hiss of olive green.",
    tags: ["snake", "print", "scales", "wild"],
    image: "snake-print",
  },
  {
    id: "67",
    name: "Zebra Print",
    category: "Y2K",
    colors: ["#ffffff", "#18181b", "#e4e4e7"],
    style: "Zebra Stripes",
    difficulty: "Medium",
    description: "Wonky monochrome zebra stripes racing across glossy white.",
    tags: ["zebra", "print", "stripes", "bold"],
    image: "zebra-print",
  },
  {
    id: "68",
    name: "Cow Print",
    category: "Cute",
    colors: ["#ffffff", "#44403c", "#fbcfe8"],
    style: "Cow Spots",
    difficulty: "Easy",
    description: "Playful inky cow patches with one bubblegum-pink accent nail.",
    tags: ["cow", "print", "cute", "spots"],
    image: "cow-print",
  },
  {
    id: "69",
    name: "Tiger Print",
    category: "Y2K",
    colors: ["#fb923c", "#18181b", "#fde047"],
    style: "Tiger Stripes",
    difficulty: "Hard",
    description: "Fiery orange base slashed with jagged black tiger stripes.",
    tags: ["tiger", "print", "stripes", "fierce"],
    image: "tiger-print",
  },
  {
    id: "70",
    name: "Marble Nails",
    category: "Elegant",
    colors: ["#ffffff", "#9ca3af", "#e5e7eb"],
    style: "White Marble",
    difficulty: "Medium",
    description: "Classic Carrara marble veining in soft grey over milky white.",
    tags: ["marble", "stone", "elegant", "white"],
    image: "marble-nails",
  },
  {
    id: "71",
    name: "Green Marble",
    category: "Elegant",
    colors: ["#166534", "#86efac", "#052e16"],
    style: "Green Marble",
    difficulty: "Hard",
    description: "Emerald marble with pale jade veins like polished malachite.",
    tags: ["marble", "green", "stone", "luxury"],
    image: "green-marble",
  },
  {
    id: "72",
    name: "Blue Marble",
    category: "Elegant",
    colors: ["#1e40af", "#93c5fd", "#dbeafe"],
    style: "Blue Marble",
    difficulty: "Hard",
    description: "Deep lapis marble streaked with icy white and sky veins.",
    tags: ["marble", "blue", "stone", "ocean"],
    image: "blue-marble",
  },
  {
    id: "73",
    name: "Purple Marble",
    category: "Elegant",
    colors: ["#6d28d9", "#c4b5fd", "#ede9fe"],
    style: "Purple Marble",
    difficulty: "Hard",
    description: "Amethyst marble with lilac lightning veins on royal purple.",
    tags: ["marble", "purple", "amethyst", "luxury"],
    image: "purple-marble",
  },
  {
    id: "74",
    name: "White Marble",
    category: "Minimalist",
    colors: ["#fafaf9", "#d6d3d1", "#ffffff"],
    style: "Marble Veins",
    difficulty: "Easy",
    description: "Barely-there grey veins whispering across clean white stone.",
    tags: ["marble", "white", "minimal", "clean"],
    image: "white-marble",
  },
  {
    id: "75",
    name: "Checkered Nails",
    category: "Y2K",
    colors: ["#18181b", "#fafaf9", "#a855f7"],
    style: "Checkerboard",
    difficulty: "Medium",
    description: "Skater checkerboard in black and white with one purple square.",
    tags: ["checkered", "print", "skater", "retro"],
    image: "checkered-nails",
  },
  {
    id: "76",
    name: "Chessboard Nails",
    category: "Minimalist",
    colors: ["#e7e5e4", "#1c1917", "#ffffff"],
    style: "Chess Grid",
    difficulty: "Medium",
    description: "Crisp stone-and-ink chessboard grid for a quiet graphic statement.",
    tags: ["chess", "checkered", "minimal", "graphic"],
    image: "chessboard-nails",
  },
  {
    id: "77",
    name: "Swirl Nails",
    category: "Y2K",
    colors: ["#f9a8d4", "#ffffff", "#a855f7"],
    style: "Candy Swirls",
    difficulty: "Medium",
    description: "Groovy candy-pink swirl bands twisting over milky white.",
    tags: ["swirl", "retro", "pink", "trippy"],
    image: "swirl-nails",
  },
  {
    id: "78",
    name: "Groovy Swirls",
    category: "Y2K",
    colors: ["#fb923c", "#fde047", "#22c55e"],
    style: "Groovy Bands",
    difficulty: "Medium",
    description: "Seventies sunset swirl bands in tangerine, gold, and avocado.",
    tags: ["swirl", "groovy", "retro", "seventies"],
    image: "groovy-swirls",
  },
  {
    id: "79",
    name: "Aura Nails",
    category: "Minimalist",
    colors: ["#f9a8d4", "#fef3c7", "#ffffff"],
    style: "Aura Glow",
    difficulty: "Easy",
    description: "Soft blush aura glowing from the center of a milky halo.",
    tags: ["aura", "glow", "gradient", "soft"],
    image: "aura-nails",
  },
  {
    id: "80",
    name: "Purple Aura Nails",
    category: "Gothic",
    colors: ["#2e1065", "#a855f7", "#e9d5ff"],
    style: "Dark Aura",
    difficulty: "Medium",
    description: "Violet aura burning at the center of a near-black plum base.",
    tags: ["aura", "purple", "dark", "glow"],
    image: "purple-aura-nails",
  },
  {
    id: "81",
    name: "Japanese Sakura Nails",
    category: "Floral",
    colors: ["#fbcfe8", "#be123c", "#fff1f2"],
    style: "Sakura Petals",
    difficulty: "Medium",
    description: "Drifting sakura blossoms with gold centers on pale spring pink.",
    tags: ["sakura", "japanese", "spring", "blossom"],
    image: "japanese-sakura-nails",
  },
  {
    id: "82",
    name: "Japanese Fan Nails",
    category: "Elegant",
    colors: ["#dc2626", "#fde68a", "#fefce8"],
    style: "Folding Fan",
    difficulty: "Hard",
    description: "Crimson folding fans with gold ribs opening over warm ivory.",
    tags: ["fan", "japanese", "gold", "festival"],
    image: "japanese-fan-nails",
  },
  {
    id: "83",
    name: "Dragon Nails",
    category: "Gothic",
    colors: ["#14532d", "#fde047", "#052e16"],
    style: "Dragon Scales",
    difficulty: "Hard",
    description: "Emerald dragon scales with golden eyes watching from the dark.",
    tags: ["dragon", "scales", "fantasy", "green"],
    image: "dragon-nails",
  },
  {
    id: "84",
    name: "Red Asian-Inspired Nails",
    category: "Elegant",
    colors: ["#b91c1c", "#fde68a", "#fef2f2"],
    style: "Lucky Red",
    difficulty: "Medium",
    description: "Lacquered lucky red with delicate gold knots for prosperity.",
    tags: ["red", "asian", "gold", "lunar"],
    image: "red-asian-inspired-nails",
  },
  {
    id: "85",
    name: "Pressed Flower Nails",
    category: "Floral",
    colors: ["#fefce8", "#f472b6", "#86efac"],
    style: "Pressed Blooms",
    difficulty: "Medium",
    description: "Real-look pressed wildflowers sealed under glass-clear gloss.",
    tags: ["pressed", "flowers", "botanical", "spring"],
    image: "pressed-flower-nails",
  },
  {
    id: "86",
    name: "Botanical Nails",
    category: "Floral",
    colors: ["#f0fdf4", "#16a34a", "#fefce8"],
    style: "Botanical Leaves",
    difficulty: "Medium",
    description: "Fine fern and eucalyptus sprigs sketched on dewy morning white.",
    tags: ["botanical", "leaves", "green", "garden"],
    image: "botanical-nails",
  },
  {
    id: "87",
    name: "Clover Nails",
    category: "Floral",
    colors: ["#16a34a", "#bbf7d0", "#fefce8"],
    style: "Lucky Clover",
    difficulty: "Easy",
    description: "Four-leaf clovers dotting a fresh meadow green for good luck.",
    tags: ["clover", "luck", "green", "spring"],
    image: "clover-nails",
  },
  {
    id: "88",
    name: "Sunflower Nails",
    category: "Floral",
    colors: ["#facc15", "#78350f", "#fef9c3"],
    style: "Sunflower Bloom",
    difficulty: "Medium",
    description: "Sunny double sunflowers with seed-brown centers on honey cream.",
    tags: ["sunflower", "yellow", "summer", "cheerful"],
    image: "sunflower-nails",
  },
  {
    id: "89",
    name: "3D Heart Nails",
    category: "Cute",
    colors: ["#f472b6", "#ffe4e6", "#be123c"],
    style: "Puffy Hearts",
    difficulty: "Hard",
    description: "Puffy jelly hearts with glossy highlights that pop off the nail.",
    tags: ["hearts", "3d", "cute", "valentine"],
    image: "3d-heart-nails",
  },
  {
    id: "90",
    name: "Bubble Nails",
    category: "Kawaii",
    colors: ["#bae6fd", "#ffffff", "#e0f2fe"],
    style: "Soap Bubbles",
    difficulty: "Easy",
    description: "Iridescent soap bubbles floating over a sheer puddle blue.",
    tags: ["bubbles", "kawaii", "blue", "playful"],
    image: "bubble-nails",
  },
  {
    id: "91",
    name: "Water Droplet Nails",
    category: "Minimalist",
    colors: ["#e0f2fe", "#38bdf8", "#ffffff"],
    style: "Rain Droplets",
    difficulty: "Medium",
    description: "Hyper-glossy rain droplets beading on a cool glass-blue base.",
    tags: ["droplets", "water", "rain", "glossy"],
    image: "water-droplet-nails",
  },
  {
    id: "92",
    name: "Mirror Chrome Nails",
    category: "Chrome",
    colors: ["#e5e7eb", "#ffffff", "#71717a"],
    style: "Mirror Chrome",
    difficulty: "Hard",
    description: "True liquid-mirror chrome buffed to a blinding silver reflection.",
    tags: ["mirror", "chrome", "silver", "metallic"],
    image: "mirror-chrome-nails",
  },
  {
    id: "93",
    name: "Icy Blue Nails",
    category: "Elegant",
    colors: ["#bae6fd", "#f0f9ff", "#0369a1"],
    style: "Glacier Ice",
    difficulty: "Medium",
    description: "Pale glacier blue with frozen crystal veins and silver frost.",
    tags: ["icy", "blue", "winter", "frost"],
    image: "icy-blue-nails",
  },
  {
    id: "94",
    name: "Snowflake Nails",
    category: "Floral",
    colors: ["#1e3a8a", "#bfdbfe", "#ffffff"],
    style: "Snowflake Lace",
    difficulty: "Hard",
    description: "Six-point crystal snowflakes etched in white over alpine navy.",
    tags: ["snowflake", "winter", "christmas", "lace"],
    image: "snowflake-nails",
  },
  {
    id: "95",
    name: "Christmas Nails",
    category: "Floral",
    colors: ["#166534", "#dc2626", "#fde68a"],
    style: "Holiday Pine",
    difficulty: "Medium",
    description: "Mini pine sprigs with ruby baubles and gold starlight for the holidays.",
    tags: ["christmas", "holiday", "pine", "festive"],
    image: "christmas-nails",
  },
  {
    id: "96",
    name: "Halloween Nails",
    category: "Gothic",
    colors: ["#18181b", "#f97316", "#a855f7"],
    style: "Haunted Night",
    difficulty: "Medium",
    description: "Pumpkin orange moons and violet bats swooping over haunted black.",
    tags: ["halloween", "spooky", "october", "bats"],
    image: "halloween-nails",
  },
  {
    id: "97",
    name: "Valentine's Nails",
    category: "Cute",
    colors: ["#f472b6", "#ffe4e6", "#be123c"],
    style: "Sweetheart Mix",
    difficulty: "Medium",
    description: "Candy hearts, tiny kisses, and love-letter pink for February fourteen.",
    tags: ["valentine", "hearts", "love", "pink"],
    image: "valentines-nails",
  },
  {
    id: "98",
    name: "Birthday Party Nails",
    category: "Cute",
    colors: ["#f9a8d4", "#fde047", "#93c5fd"],
    style: "Confetti Pop",
    difficulty: "Easy",
    description: "Sprinkle confetti bursting over pastel party pink, ready to celebrate.",
    tags: ["birthday", "confetti", "party", "fun"],
    image: "birthday-party-nails",
  },
  {
    id: "99",
    name: "Bridal Pearl Nails",
    category: "Elegant",
    colors: ["#fdf4ff", "#ffffff", "#e9d5ff"],
    style: "Pearl Veil",
    difficulty: "Medium",
    description: "Sheer pearl veil with a single luminous bead for walking down the aisle.",
    tags: ["bridal", "pearl", "wedding", "white"],
    image: "bridal-pearl-nails",
  },
  {
    id: "100",
    name: "Custom \"Janella\" Signature Nails",
    category: "Elegant",
    colors: ["#f9a8d4", "#fdf4ff", "#a855f7"],
    style: "Janella Monogram",
    difficulty: "Hard",
    description: "Blush-to-lilac artistry finished with a hand-painted J monogram.",
    tags: ["signature", "custom", "monogram", "janella"],
    image: "janella-signature-nails",
  },
];

export const CATEGORIES: string[] = Array.from(
  new Set(DESIGNS.map((d) => d.category))
).sort();

export const DESIGNS_BY_ID: Record<string, NailDesign> = Object.fromEntries(
  DESIGNS.map((d) => [d.id, d])
);

if (DESIGNS.length !== 100) throw new Error("Expected 100 designs");
